import type { MenuItem } from "@/app/context/CartContext";

export interface MenuCategory {
  id: string;
  name: string;
  description: string | null;
  display_order: number;
}

export const CATEGORIES: MenuCategory[] = [
  { id: "appetizers",    name: "Appetizers",    description: null, display_order: 1  },
  { id: "dips",          name: "Dips",          description: null, display_order: 2  },
  { id: "salads-soups",  name: "Salads & Soups",description: null, display_order: 3  },
  { id: "nachos",        name: "Nachos",        description: null, display_order: 4  },
  { id: "quesadillas",   name: "Quesadillas",   description: null, display_order: 5  },
  { id: "street-food",   name: "Street Food",   description: null, display_order: 6  },
  { id: "burritos",      name: "Burritos",      description: null, display_order: 7  },
  { id: "enchiladas",    name: "Enchiladas",    description: null, display_order: 8  },
  { id: "fajitas",       name: "Fajitas",       description: null, display_order: 9  },
  { id: "most-wanted",   name: "Most Wanted",   description: null, display_order: 10 },
  { id: "chicken",       name: "Chicken",       description: null, display_order: 11 },
  { id: "asadero-grill", name: "Asadero Grill", description: null, display_order: 12 },
  { id: "birria",        name: "Birria Lovers", description: null, display_order: 13 },
  { id: "lo-mas-rico",   name: "Lo Más Rico",   description: null, display_order: 14 },
  { id: "from-the-sea",  name: "From The Sea",  description: null, display_order: 15 },
  { id: "del-mar",       name: "Del Mar",       description: null, display_order: 16 },
  { id: "veggies",       name: "Veggies",       description: null, display_order: 17 },
  { id: "kids",          name: "Kids",          description: null, display_order: 18 },
  { id: "a-la-carte",    name: "A La Carte",    description: null, display_order: 19 },
  { id: "sides",         name: "Sides",         description: null, display_order: 20 },
];

// Curated Unsplash photo pools per category
const P = {
  wings:      "https://images.unsplash.com/photo-1527477396000-e27163b481c2?w=800&q=80",
  calamari:   "/calimari-shrimp.jpeg",
  sampler:    "/sampler.jpeg",
  fries:      "/fries.jpeg",
  asadaFries: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&q=80",
  jalap:      "/texas-twinkles.jpeg",
  empanada:   "/empanadas.jpeg",
  corn:       "https://images.unsplash.com/photo-1551754655-cd27e38d2076?w=800&q=80",
  guac:       "/guac.jpeg",
  queso:      "https://images.unsplash.com/photo-1620897240085-d618c6b9bfda?w=800&q=80",
  dip:        "https://images.unsplash.com/photo-1576107232684-1279f17d4a48?w=800&q=80",
  salad:      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
  salad2:     "https://images.unsplash.com/photo-1540420773420-3366772f4999?w=800&q=80",
  soup:       "https://images.unsplash.com/photo-1547592166-23ac45744acd?w=800&q=80",
  nachos:     "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=800&q=80",
  nachos2:    "https://images.unsplash.com/photo-1586816879360-004f5b0c51e3?w=800&q=80",
  quesadilla: "https://images.unsplash.com/photo-1599974579688-8dbdd335c77f?w=800&q=80",
  quesadilla2:"https://images.unsplash.com/photo-1618897996318-5a901fa9b3a9?w=800&q=80",
  tacos:      "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
  tacos2:     "https://images.unsplash.com/photo-1611250188496-e966043a0629?w=800&q=80",
  torta:      "https://images.unsplash.com/photo-1509722747041-616f39b57569?w=800&q=80",
  flautas:    "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
  sopes:      "https://images.unsplash.com/photo-1584255014502-4f2d04c99e07?w=800&q=80",
  burrito:    "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=800&q=80",
  burrito2:   "https://images.unsplash.com/photo-1552332386-f8dd00dc2f85?w=800&q=80",
  enchilada:  "https://images.unsplash.com/photo-1551504734-5da27d7ffeea?w=800&q=80",
  enchilada2: "https://images.unsplash.com/photo-1584477812540-b8b0f3b5e4e7?w=800&q=80",
  fajitas:    "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&q=80",
  fajitas2:   "https://images.unsplash.com/photo-1593030668452-9c54c0ab34b4?w=800&q=80",
  parrillada: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&q=80",
  pasta:      "https://images.unsplash.com/photo-1473093295043-cdd812d0e601?w=800&q=80",
  burger:     "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&q=80",
  ribs:       "https://images.unsplash.com/photo-1544025162-d76538b2a681?w=800&q=80",
  bowl:       "https://images.unsplash.com/photo-1546069901-ba9599a7e63c?w=800&q=80",
  steak:      "https://images.unsplash.com/photo-1546964124-0cce460f38ef?w=800&q=80",
  steak2:     "https://images.unsplash.com/photo-1558030006-f6097c039575?w=800&q=80",
  steak3:     "https://images.unsplash.com/photo-1544025162-d76538b2a681?w=800&q=80",
  chicken:    "https://images.unsplash.com/photo-1598103442097-1b6b4b8c8a1f?w=800&q=80",
  chicken2:   "https://images.unsplash.com/photo-1504674900247-0877df9cc836?w=800&q=80",
  chicken3:   "https://images.unsplash.com/photo-1604503468163-4c68b54f7f37?w=800&q=80",
  birria:     "https://images.unsplash.com/photo-1611250188496-e966043a0629?w=800&q=80",
  birria2:    "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=800&q=80",
  pizza:      "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&q=80",
  shrimp:     "https://images.unsplash.com/photo-1559410545-0bdcd187e0a6?w=800&q=80",
  shrimp2:    "https://images.unsplash.com/photo-1565680018093-ebb6b9ab5460?w=800&q=80",
  salmon:     "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?w=800&q=80",
  seafood:    "https://images.unsplash.com/photo-1565680018093-ebb6b9ab5460?w=800&q=80",
  ceviche:    "https://images.unsplash.com/photo-1615361200141-f45040f367be?w=800&q=80",
  ceviche2:   "https://images.unsplash.com/photo-1601050690293-8890987b8b9e?w=800&q=80",
  oysters:    "https://images.unsplash.com/photo-1569001561548-f9e4d4e6d475?w=800&q=80",
  fish:       "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=800&q=80",
  lobster:    "https://images.unsplash.com/photo-1550317138-10000687a72b?w=800&q=80",
  rice:       "https://images.unsplash.com/photo-1536304929831-ee1ca9d44906?w=800&q=80",
  veggie:     "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?w=800&q=80",
  vegBurger:  "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&q=80",
  kidsMeal:   "https://images.unsplash.com/photo-1555396273-367ea4eb4db5?w=800&q=80",
  tamal:      "https://images.unsplash.com/photo-1584255014502-4f2d04c99e07?w=800&q=80",
  molcajete:  "https://images.unsplash.com/photo-1529193591184-b1d58069ecdd?w=800&q=80",
};

export const MENU_ITEMS: MenuItem[] = [
  // APPETIZERS
  { id: "app-1",  name: "Asadero Sampler",        description: "Deep-fried shrimp, tilapia, calamari, mozzarella sticks, and chicken tenders. Served with ranch, buffalo sauce and our golden sauce.", price: 24.99, category_id: "appetizers", image_url: P.sampler,    is_featured: true,  tags: [] },
  { id: "app-2",  name: "Calamari N Shrimp",       description: "Deep fried calamari and shrimp breaded with jalapeños served with BBQ sauce, Gold sauce & Buffalo sauce.", price: 19.99, category_id: "appetizers", image_url: P.calamari,   is_featured: false, tags: [] },
  { id: "app-3",  name: "Chicken Wings (10 pcs)",  description: "Served with french fries, choice of sauces: Mango Habanero, Garlic, Buffalo, or Spicy.", price: 19.99, category_id: "appetizers", image_url: P.wings,      is_featured: false, tags: [] },
  { id: "app-4",  name: "Asada Fries",             description: "Cast iron skillet sizzling steak, fries, pico de gallo, guacamole, sour cream and mixed cheese, cheese sauce.", price: 17.99, category_id: "appetizers", image_url: P.asadaFries, is_featured: false, tags: [] },
  { id: "app-5",  name: "Texas Fries",             description: "Cast iron skillet sizzling fries, steak, chicken, shrimp, chorizo, grilled onion topped with cheese dip, sour cream, pickled jalapeños, light cilantro and queso fresco.", price: 18.99, category_id: "appetizers", image_url: P.fries,      is_featured: false, tags: [] },
  { id: "app-6",  name: "Texas Twinkles (3)",      description: "Whole jalapeño stuffed with cream cheese, mozzarella, brisket, roasted corn, wrapped with bacon and topped with BBQ sauce.", price: 13.99, category_id: "appetizers", image_url: P.jalap,      is_featured: false, tags: [] },
  { id: "app-7",  name: "Birria Flautas",          description: "Three flour tortillas stuffed with birria topped with sour cream, queso fresco, and consomé.", price: 14.99, category_id: "appetizers", image_url: P.flautas,    is_featured: false, tags: [] },
  { id: "app-8",  name: "Empanadas",               description: "Three empanadas stuffed choice of chicken, ground beef, or ham and cheese, served with golden sauce.", price: 13.99, category_id: "appetizers", image_url: P.empanada,   is_featured: false, tags: [] },
  { id: "app-9",  name: "Mexican Corn",            description: "Traditional, Hot Cheetos, Blue Heat, Fuego, or Asado.", price: 5.99, category_id: "appetizers", image_url: P.corn,       is_featured: false, tags: [] },
  { id: "app-10", name: "Table Side Guacamole",    description: "Fresh Mexican guacamole made in front of your table.", price: 12.99, category_id: "appetizers", image_url: P.guac,       is_featured: false, tags: [] },

  // DIPS
  { id: "dip-1", name: "Cowboy Dip",      description: "Chorizo, pico de gallo, roasted corn, black beans, and cheese dip.", price: 12.99, category_id: "dips", image_url: P.queso,    is_featured: false, tags: [] },
  { id: "dip-2", name: "Texas Dip",       description: "Steak, pollo, shrimp and pico mixed with cheese sauce.", price: 11.99, category_id: "dips", image_url: P.dip,      is_featured: false, tags: [] },
  { id: "dip-3", name: "Queso Fundido",   description: "Hot melted cheese and chorizo.", price: 11.99, category_id: "dips", image_url: P.queso,    is_featured: false, tags: [] },
  { id: "dip-4", name: "Chori Cheese Dip",description: "Chorizo (Mexican sausage) with cheese sauce.", price: 11.99, category_id: "dips", image_url: P.queso,    is_featured: false, tags: [] },
  { id: "dip-5", name: "Cheese Dip",      description: null, price: 5.49, category_id: "dips", image_url: P.queso,    is_featured: false, tags: [] },
  { id: "dip-6", name: "Guacamole Dip",   description: null, price: 5.49, category_id: "dips", image_url: P.guac,     is_featured: false, tags: [] },
  { id: "dip-7", name: "Bean Dip",        description: null, price: 7.99, category_id: "dips", image_url: P.dip,      is_featured: false, tags: [] },
  { id: "dip-8", name: "Ground Beef Dip", description: null, price: 7.99, category_id: "dips", image_url: P.dip,      is_featured: false, tags: [] },

  // SALADS & SOUPS
  { id: "ss-1", name: "Supreme Salad",            description: "A bed of greens, topped choice of protein, tomatoes, strawberry, avocado, pecans, croutons, cucumber, light queso fresco.", price: 16.99, category_id: "salads-soups", image_url: P.salad,  is_featured: false, tags: [] },
  { id: "ss-2", name: "Tropical Mango Avocado",   description: "A bed of greens topped with grilled chicken or steak, onion, pepper, tomatoes, avocado, and mangos.", price: 17.99, category_id: "salads-soups", image_url: P.salad2, is_featured: false, tags: [] },
  { id: "ss-3", name: "Rib Eye Salad",            description: "A crispy flour tortilla filled with your choice of grilled steak or chicken, rice, pico de gallo, guacamole, grated cheese and sour cream.", price: 14.99, category_id: "salads-soups", image_url: P.salad,  is_featured: false, tags: [] },
  { id: "ss-4", name: "Taco Loco",                description: "Grilled chicken, steak, shrimp, mushroom, zucchini, tomatoes, rice and topped with cheese sauce.", price: 17.99, category_id: "salads-soups", image_url: P.bowl,   is_featured: false, tags: [] },
  { id: "ss-5", name: "Taco Salad",               description: "A crispy flour tortilla filled with beef or chicken, lettuce, tomatoes, grated cheese and sour cream.", price: 10.99, category_id: "salads-soups", image_url: P.salad2, is_featured: false, tags: [] },
  { id: "ss-6", name: "Chicken Soup",             description: "Chunks of chicken with rice topped with fresh avocado, pico de gallo and tortilla strip.", price: 8.99,  category_id: "salads-soups", image_url: P.soup,   is_featured: false, tags: [] },
  { id: "ss-7", name: "Pozole",                   description: "Traditional Mexican soup, made from hominy and chicken. Seasoned and garnished with shredded lettuce, onions, radishes.", price: 12.99, category_id: "salads-soups", image_url: P.soup,   is_featured: false, tags: [] },

  // NACHOS
  { id: "nac-1", name: "Nachos Cheese or Beans",               description: null, price: 11.99, category_id: "nachos", image_url: P.nachos,  is_featured: false, tags: [] },
  { id: "nac-2", name: "Nachos Ground Beef or Shredded Chicken",description: null, price: 13.99, category_id: "nachos", image_url: P.nachos2, is_featured: false, tags: [] },
  { id: "nac-3", name: "Hawaiian Nachos",                       description: "Chicken, steak, shrimp, pineapple, bacon, ham topped with our creamy pineapple sauce and bang bang sauce.", price: 19.99, category_id: "nachos", image_url: P.nachos,  is_featured: false, tags: [] },
  { id: "nac-4", name: "Asada Nachos",                          description: "A bed of beans, steak, pico de gallo, guacamole and sour cream.", price: 18.99, category_id: "nachos", image_url: P.nachos2, is_featured: false, tags: [] },
  { id: "nac-5", name: "Buffalo Nachos",                        description: "Chicken tenders buffalo style topped with pico de gallo, jalapeños, cilantro, roasted corn, queso fresco and crema.", price: 18.99, category_id: "nachos", image_url: P.nachos,  is_featured: false, tags: [] },
  { id: "nac-6", name: "Fiesta Nachos",                         description: "Chicken, steak, shrimp, pork, chorizo, mushroom, zucchini, onions, and tomatoes.", price: 20.99, category_id: "nachos", image_url: P.nachos2, is_featured: false, tags: [] },
  { id: "nac-7", name: "Don Nachos",                            description: "Ground beef, beans, corn, jalapeños, cilantro, topped with crema.", price: 17.99, category_id: "nachos", image_url: P.nachos,  is_featured: false, tags: [] },
  { id: "nac-8", name: "Nachos Fajitas",                        description: "Chicken, steak or shrimp, grilled onions and bell peppers.", price: 18.99, category_id: "nachos", image_url: P.nachos2, is_featured: false, tags: [] },

  // QUESADILLAS
  { id: "ques-1", name: "Quesadillas Cheese or Beans",               description: null, price: 11.99, category_id: "quesadillas", image_url: P.quesadilla,  is_featured: false, tags: [] },
  { id: "ques-2", name: "Quesadillas Ground Beef or Shredded Chicken",description: null, price: 13.99, category_id: "quesadillas", image_url: P.quesadilla2, is_featured: false, tags: [] },
  { id: "ques-3", name: "Grill Quesadilla",                           description: "Flour tortilla filled with cheese, choice of steak or chicken served with pico de gallo & sour cream.", price: 14.99, category_id: "quesadillas", image_url: P.quesadilla,  is_featured: false, tags: [] },
  { id: "ques-4", name: "Quesadillas Rancheras (3)",                  description: "Three cheese quesadillas, topped with chicken or steak, green sauce, pico de gallo and mixed cheese.", price: 16.99, category_id: "quesadillas", image_url: P.quesadilla2, is_featured: false, tags: [] },
  { id: "ques-5", name: "Cheesesteak Quesadillas",                    description: "Flour tortilla filled with your choice of steak or grilled chicken, topped with cheese sauce. Served with rice and beans.", price: 16.99, category_id: "quesadillas", image_url: P.quesadilla,  is_featured: false, tags: [] },
  { id: "ques-6", name: "Quesadillas Fajita",                         description: "Flour tortillas filled with choice of chicken or steak, cheese, onion, bell peppers. Served with garden salad, pico de gallo, sour cream, guacamole and rice.", price: 18.99, category_id: "quesadillas", image_url: P.quesadilla2, is_featured: false, tags: [] },

  // STREET FOOD
  { id: "sf-1", name: "Torta",                  description: "A sandwich bun stuffed with your choice of meat, lettuce, pico de gallo, avocado, jalapeños, light beans and mayo.", price: 16.99, category_id: "street-food", image_url: P.torta,   is_featured: false, tags: [] },
  { id: "sf-2", name: "Street Tacos (3)",        description: "Three corn or flour tortillas, choice of meat, topped with onion and cilantro served with rice and beans.", price: 15.99, category_id: "street-food", image_url: P.tacos,   is_featured: false, tags: [] },
  { id: "sf-3", name: "Hot Cheeto Tacos (3)",    description: "Three corn or flour tortillas, choice of meat, topped with pico de gallo, corn, cheese, crema and hot Cheetos. Served with rice and beans.", price: 17.99, category_id: "street-food", image_url: P.tacos2,  is_featured: false, tags: [] },
  { id: "sf-4", name: "Bone Marrow Taco (3)",    description: "Three bone marrow tacos, choice of protein, light grilled onions. Served with guacamole and two cheese quesadillas.", price: 21.99, category_id: "street-food", image_url: P.tacos,   is_featured: true,  tags: [] },
  { id: "sf-5", name: "Sopes (3)",               description: "Three corn based dough with bed of lettuce topped with light beans, choice of meat, pico de gallo, crema, avocados and queso fresco.", price: 16.99, category_id: "street-food", image_url: P.sopes,   is_featured: false, tags: [] },
  { id: "sf-6", name: "Flautas (4)",             description: "Four tortillas fried with your choice of meat, lettuce, red cabbage, queso fresco, pico de gallo, sour cream and gold sauce.", price: 15.99, category_id: "street-food", image_url: P.flautas, is_featured: false, tags: [] },
  { id: "sf-7", name: "Lettuce Wrap Tacos (3)",  description: "Healthy romaine lettuce wraps sautéed with bell peppers, pico de gallo, roasted corn, onion, crema, and shredded cheese, served with rice and black beans.", price: 16.99, category_id: "street-food", image_url: P.tacos2,  is_featured: false, tags: [] },
  { id: "sf-8", name: "Gorditas (2)",            description: "Two corn based dough your choice of meat, lettuce, shredded cheese, tomato and light beans. Served with rice and beans.", price: 14.99, category_id: "street-food", image_url: P.sopes,   is_featured: false, tags: [] },

  // BURRITOS
  { id: "bur-1", name: "Asadero Burrito",    description: "Stuffed with steak, grilled chicken, rice, red salsa, beans, topped with cheese sauce, chorizo, pineapple and shrimp.", price: 19.99, category_id: "burritos", image_url: P.burrito,  is_featured: true,  tags: [] },
  { id: "bur-2", name: "Burrito Mexico",     description: "Steak or grilled chicken, rice, shredded cheese and beans, topped with cheese sauce, green sauce, red sauce and cilantro.", price: 18.99, category_id: "burritos", image_url: P.burrito2, is_featured: false, tags: [] },
  { id: "bur-3", name: "Grill Burrito",      description: "Choice of filling, rice, cheese, lettuce, corn, black beans, pico de gallo, and guacamole. Served with french fries.", price: 18.99, category_id: "burritos", image_url: P.burrito,  is_featured: false, tags: [] },
  { id: "bur-4", name: "Cali Burrito",       description: "Rice, shredded cheese and guacamole, fries. Choice of meat, topped with bang bang sauce and creamy green sauce and sour cream.", price: 18.99, category_id: "burritos", image_url: P.burrito2, is_featured: false, tags: [] },
  { id: "bur-5", name: "King Kong Burrito",  description: "Bacon wrapped burrito filled with steak, pastor, chorizo, lettuce, pico de gallo, cheese, sour cream and rice.", price: 21.99, category_id: "burritos", image_url: P.burrito,  is_featured: false, tags: [] },
  { id: "bur-6", name: "Cheesesteak Burrito",description: "Choice of steak or chicken with grilled onions, shredded cheese topped with lettuce, pico de gallo, and cheese sauce. Served with rice and beans.", price: 19.99, category_id: "burritos", image_url: P.burrito2, is_featured: false, tags: [] },
  { id: "bur-7", name: "Burrito Hawaiano",   description: "Grilled chicken, ham, bacon sausage, pineapple, lettuce, red onion, white rice, topped with cheese dip.", price: 19.99, category_id: "burritos", image_url: P.burrito,  is_featured: false, tags: [] },
  { id: "bur-8", name: "Cabos Burrito",      description: "Breaded shrimp, lobster, lettuce, pico de mango, white rice, black beans, avocado, topped with golden sauce.", price: 22.99, category_id: "burritos", image_url: P.burrito2, is_featured: false, tags: [] },

  // ENCHILADAS
  { id: "enc-1", name: "Omar's Enchiladas",    description: "Three enchiladas stuffed with your choice of steak or grilled chicken, one topped with bang sauce, one with mole sauce and one creamy green sauce, served with rice.", price: 17.99, category_id: "enchiladas", image_url: P.enchilada,  is_featured: true,  tags: [] },
  { id: "enc-2", name: "Enchiladas Bang Bang", description: "Three chicken enchiladas topped with bang sauce and sour cream, pico de gallo served with rice.", price: 16.99, category_id: "enchiladas", image_url: P.enchilada2, is_featured: false, tags: [] },
  { id: "enc-3", name: "Enchiladas Suizas",    description: "Three chicken enchiladas topped with creamy green sauce, Swiss cheese, served with rice.", price: 16.99, category_id: "enchiladas", image_url: P.enchilada,  is_featured: false, tags: [] },
  { id: "enc-4", name: "Enchiladas con Mole",  description: "Three chicken enchiladas topped with traditional Mexican mole sauce, sour cream, queso fresco and served with rice.", price: 16.99, category_id: "enchiladas", image_url: P.enchilada2, is_featured: false, tags: [] },
  { id: "enc-5", name: "Enchiladas Jalisco",   description: "Three enchiladas stuffed with chicken or ground beef topped with red salsa, cheese sauce, onion and chorizo served with rice and beans.", price: 16.99, category_id: "enchiladas", image_url: P.enchilada,  is_featured: false, tags: [] },
  { id: "enc-6", name: "Enchiladas Poblana",   description: "Three enchiladas stuffed with grilled chicken and spinach, topped with our special poblano sauce, sour cream and two colored pepper. Served with rice and black beans.", price: 16.99, category_id: "enchiladas", image_url: P.enchilada2, is_featured: false, tags: [] },
  { id: "enc-7", name: "Enchilada Suprema",    description: "(5) Enchiladas: Cheese, Ground Beef, Shredded Chicken, Beans, Birria. Topped with red sauce, lettuce, tomatoes, sour cream, shredded cheese.", price: 17.99, category_id: "enchiladas", image_url: P.enchilada,  is_featured: false, tags: [] },

  // FAJITAS
  { id: "faj-1", name: "Steak or Chicken Fajitas",         description: "All fajitas are cooked with onions & mixed color bell peppers. Served with rice, beans, guacamole salad, sour cream and pico de gallo.", price: 21.99, category_id: "fajitas", image_url: P.fajitas,    is_featured: false, tags: [] },
  { id: "faj-2", name: "Shrimp, Tilapia, or Lobster Fajitas",description: "All fajitas are cooked with onions & mixed color bell peppers. Served with rice, beans, guacamole salad, sour cream and pico de gallo.", price: 22.99, category_id: "fajitas", image_url: P.fajitas2,   is_featured: false, tags: [] },
  { id: "faj-3", name: "Asadero Hawaiana",                 description: "Grilled chicken, steak, shrimp, pineapple, ham, topped with cheese sauce.", price: 23.99, category_id: "fajitas", image_url: P.fajitas,    is_featured: false, tags: [] },
  { id: "faj-4", name: "Texanas Fajitas",                  description: "Grilled chicken, steak, shrimp.", price: 23.99, category_id: "fajitas", image_url: P.fajitas2,   is_featured: false, tags: [] },
  { id: "faj-5", name: "Maya Fajitas",                     description: "Chicken, steak, onions, cactus, poblano & chorizo cheese.", price: 24.99, category_id: "fajitas", image_url: P.fajitas,    is_featured: false, tags: [] },
  { id: "faj-6", name: "Flaming Cheese Fajitas",           description: "Grilled chicken, steak, onion, zucchini, mushrooms, topped with flaming melted cheese. For one.", price: 27.99, category_id: "fajitas", image_url: P.fajitas2,   is_featured: true,  tags: [] },
  { id: "faj-7", name: "Parrillada",                       description: "Steak, ribs, chorizo, shrimp, grilled chicken cooked with bell peppers and onions, topped with cheese quesadilla.", price: 31.99, category_id: "fajitas", image_url: P.parrillada, is_featured: false, tags: [] },
  { id: "faj-8", name: "Charola Paisa",                    description: "Shrimp, steak, chicken, carnitas, sausage, pork belly, rib, corn, Mexican guacamole.", price: 62.99, category_id: "fajitas", image_url: P.parrillada, is_featured: false, tags: [] },
  { id: "faj-9", name: "El Asadero Parrillada",            description: "Ribeye steak, roasted chicken, BBQ ribs, ribeye ribs, chorizo, shrimp, cactus, corn on a cob, queso fresco, sausages.", price: 72.99, category_id: "fajitas", image_url: P.parrillada, is_featured: false, tags: [] },

  // MOST WANTED
  { id: "mw-1",  name: "Penn Pasta",               description: "Penne, grilled chicken, pico de gallo, Alfredo sauce, grated cheese.", price: 17.99, category_id: "most-wanted", image_url: P.pasta,      is_featured: false, tags: [] },
  { id: "mw-2",  name: "Carbonara Fettuccine",      description: "Fettuccine pasta, Alfredo sauce, grilled chicken, shrimp, bacon bites, grated cheese, spinach and roasted red pepper.", price: 19.99, category_id: "most-wanted", image_url: P.pasta,      is_featured: false, tags: [] },
  { id: "mw-3",  name: "Mini Trompitos",            description: "Four mini trompos, layers of pastor, onion, pineapple. Served with garden salad, avocado slices and rice.", price: 22.99, category_id: "most-wanted", image_url: P.tacos2,     is_featured: false, tags: [] },
  { id: "mw-4",  name: "Brochetas",                 description: "One brocheta grilled chicken, one brocheta steak, and sausage (pork) with mixed color bell peppers, onion, served with garden salad, avocado slices and rice.", price: 24.99, category_id: "most-wanted", image_url: P.parrillada, is_featured: false, tags: [] },
  { id: "mw-5",  name: "BBQ Ribs",                  description: "Half rack ribs, BBQ sauce, coleslaw, Mac N Cheese.", price: 23.99, category_id: "most-wanted", image_url: P.ribs,       is_featured: false, tags: [] },
  { id: "mw-6",  name: "El Asadero Bowl",           description: "Choice of ground beef, chicken, or vegetables. Rice, melted cheese, black beans, lettuce, sour cream, pico de gallo, roasted corn, red salsa, golden sauce and mixed with three cheeses.", price: 14.99, category_id: "most-wanted", image_url: P.bowl,       is_featured: false, tags: [] },
  { id: "mw-7",  name: "Luis Special",              description: "Rice, steak, chicken, shrimp, onion, poblano peppers, mushrooms, zucchini, tomatoes and nopales. Cheese sauce and red hot peppers.", price: 20.99, category_id: "most-wanted", image_url: P.fajitas,    is_featured: false, tags: [] },
  { id: "mw-8",  name: "Tamales Chingones",         description: "Three pork tamales, a bed of black beans, topped with red cabbage, lettuce, pico de mango, avocado, cheese sauce, sour cream, queso fresco and gold sauce.", price: 17.99, category_id: "most-wanted", image_url: P.tamal,      is_featured: false, tags: [] },
  { id: "mw-9",  name: "Lupe Burger",               description: "2 beef patties, cheese, lettuce, bacon, mushrooms, peppers, onions, shrimp, covered with our golden sauce. Served with french fries.", price: 19.99, category_id: "most-wanted", image_url: P.burger,     is_featured: false, tags: [] },
  { id: "mw-10", name: "Compa Burger",              description: "Two beef patties, white cheese, lettuce, tomato, bacon, ham, pineapple, covered with our golden sauce. Served with french fries.", price: 19.99, category_id: "most-wanted", image_url: P.burger,     is_featured: false, tags: [] },
  { id: "mw-11", name: "Roman Tacos",               description: "4 crispy mini corn tortillas, choice of shredded chicken or ground beef, cabbage, lettuce, pico de gallo, queso, sour cream and guacamole.", price: 14.99, category_id: "most-wanted", image_url: P.tacos,      is_featured: false, tags: [] },
  { id: "mw-12", name: "Chimichangas",              description: "Two flour tortillas rolled up stuffed in your choice of ground beef or shredded chicken, covered with cheese sauce served with rice, beans and guacamole salad.", price: 16.99, category_id: "most-wanted", image_url: P.burrito,    is_featured: false, tags: [] },
  { id: "mw-13", name: "Hawaii Changa",             description: "Flour tortilla rolled up stuffed in grilled chicken topped with cheese sauce, pineapple, ham and served with rice and guacamole salad.", price: 17.99, category_id: "most-wanted", image_url: P.burrito2,   is_featured: false, tags: [] },
  { id: "mw-14", name: "Alambre",                   description: "Choice of chicken or steak cooked with bacon, onions, bell peppers, pineapple, topped with shredded cheese and served with rice, beans and guacamole salad.", price: 21.99, category_id: "most-wanted", image_url: P.fajitas,    is_featured: false, tags: [] },
  { id: "mw-15", name: "Carnitas",                  description: "Tender fried pork, served with rice, beans, guacamole, pico de gallo, lettuce and jalapeños.", price: 18.99, category_id: "most-wanted", image_url: P.parrillada, is_featured: false, tags: [] },
  { id: "mw-16", name: "Molcajete",                 description: "Steak, chicken, chorizo and shrimp, queso fresco, grilled with Mexican onions, cactus and marinated in red sauce, green sauce and covered with cheese. Served in sizzling hot stone molcajete bowl, with rice, charro beans and guacamole salad.", price: 27.99, category_id: "most-wanted", image_url: P.molcajete,  is_featured: false, tags: [] },
  { id: "mw-17", name: "El Asadero Molcajete",      description: "Steak, chicken, ribeye ribs, pork chops, Mexican chorizo and shrimp, queso, green sauce, red sauce, grilled with Mexican onions, cactus and marinated in red sauce and covered with cheese. Sizzling hot stone molcajete bowl, with rice, charro beans and guacamole salad.", price: 33.99, category_id: "most-wanted", image_url: P.molcajete,  is_featured: true,  tags: [] },

  // CHICKEN
  { id: "ch-1", name: "Bang Bang Chicken",description: "A bed of rice, chicken breast, onion, mushrooms, tomatoes, zucchini topped with our signature Bang Bang sauce.", price: 18.99, category_id: "chicken", image_url: P.chicken,  is_featured: false, tags: [] },
  { id: "ch-2", name: "Bourbon Chicken",  description: "Famous bourbon chicken a bed of white rice, juicy chicken breast, topped with bourbon sauce served with asparagus and steamed vegetables.", price: 19.99, category_id: "chicken", image_url: P.chicken3, is_featured: false, tags: [] },
  { id: "ch-3", name: "Pollo con Mole",   description: "A bed of rice, grilled vegetables, mushrooms, zucchini, onion topped with roasted half chicken, topped with mole.", price: 21.99, category_id: "chicken", image_url: P.chicken2, is_featured: false, tags: [] },
  { id: "ch-4", name: "Pollo Santa Fe",   description: "Chicken breast topped with shrimp, cheese sauce, jalapeños and bell peppers. Served with rice and beans.", price: 19.99, category_id: "chicken", image_url: P.chicken,  is_featured: false, tags: [] },
  { id: "ch-5", name: "Roasted Chicken",  description: "Roasted half chicken, smoke sausage, homemade fries, and roasted corn.", price: 22.99, category_id: "chicken", image_url: P.chicken2, is_featured: false, tags: [] },
  { id: "ch-6", name: "Pollo Loco",       description: "Grilled chicken covered with cheese, served with onions, mushrooms, tomatoes, zucchini and rice.", price: 18.99, category_id: "chicken", image_url: P.chicken3, is_featured: false, tags: [] },
  { id: "ch-7", name: "Arroz con Pollo",  description: "Grilled chicken over a bed of rice covered with cheese sauce.", price: 16.99, category_id: "chicken", image_url: P.chicken,  is_featured: false, tags: [] },
  { id: "ch-8", name: "Chorizo Pollo",    description: "Chicken strips mixed with chorizo (Mexican sausage), pineapple, topped with melted cheese and served with rice and beans.", price: 18.99, category_id: "chicken", image_url: P.chicken3, is_featured: false, tags: [] },
  { id: "ch-9", name: "Pollo Chipotle",   description: "Grilled chicken breast, topped with creamy chipotle sauce, served with rice, lettuce, avocado and pico de gallo.", price: 18.99, category_id: "chicken", image_url: P.chicken2, is_featured: false, tags: [] },

  // ASADERO GRILL
  { id: "ag-1",  name: "Chef Special",              description: "Sirloin steak, shrimp, onion, mushrooms, jalapeños topped with shredded cheese. Served with french fries and broccoli.", price: 29.99, category_id: "asadero-grill", image_url: P.steak,   is_featured: true,  tags: [] },
  { id: "ag-2",  name: "Carne Asada / Pollo Asada", description: "Choice of sirloin steak, chicken or mixed. Grilled onions, served with rice, charro beans and guacamole salad.", price: 26.99, category_id: "asadero-grill", image_url: P.steak2,  is_featured: false, tags: [] },
  { id: "ag-3",  name: "Cowboy Steak",              description: "Served with homemade fries and steamed vegetables.", price: 63.99, category_id: "asadero-grill", image_url: P.steak,   is_featured: false, tags: [] },
  { id: "ag-4",  name: "T-Bone Baby",               description: "12oz. T-bone steak, served with roasted red potatoes, whole roasted mushrooms and asparagus.", price: 26.99, category_id: "asadero-grill", image_url: P.steak3,  is_featured: false, tags: [] },
  { id: "ag-5",  name: "Poblano Mar y Tierra",      description: "Skirt steak with poblano, shrimp topped with cheese dip, served with mashed potatoes and baby cabbage fried.", price: 28.99, category_id: "asadero-grill", image_url: P.steak2,  is_featured: false, tags: [] },
  { id: "ag-6",  name: "Filet Mignon",              description: "Filet mignon, shrimp, served with asparagus wrapped with bacon.", price: 34.99, category_id: "asadero-grill", image_url: P.steak,   is_featured: false, tags: [] },
  { id: "ag-7",  name: "Surf & Turf",               description: "Sirloin steak, lobster tail, and baby cabbage fried.", price: 42.99, category_id: "asadero-grill", image_url: P.steak3,  is_featured: false, tags: [] },
  { id: "ag-8",  name: "Steak Sirloin",             description: "Prime 14oz. Certified Angus Beef, served with french fries and garden salad.", price: 27.99, category_id: "asadero-grill", image_url: P.steak2,  is_featured: false, tags: [] },
  { id: "ag-9",  name: "Baby Lamb Chops",           description: "Four lamb chops served with rice, garden salad, avocado slices and mashed potatoes.", price: 32.99, category_id: "asadero-grill", image_url: P.steak,   is_featured: false, tags: [] },
  { id: "ag-10", name: "El Toro Steak",             description: "Rib eye steak topped with our creamy special sauce, shrimp and spinach. Served with rice, avocado and garden salad.", price: 26.99, category_id: "asadero-grill", image_url: P.steak3,  is_featured: false, tags: [] },
  { id: "ag-11", name: "Costillas de Res",          description: "Ribeye ribs, grilled onion, served with rice, charro beans and guacamole salad.", price: 24.99, category_id: "asadero-grill", image_url: P.ribs,    is_featured: false, tags: [] },
  { id: "ag-12", name: "Tomahawk Steak",            description: "Tomahawk steak served with beans, guacamole, grilled nopal, grilled onions, tomatoes and chiles toreados.", price: 120.00, category_id: "asadero-grill", image_url: P.steak2,  is_featured: false, tags: [] },
  { id: "ag-13", name: "T-Bone Mexicano",           description: "T-bone steak, onion, tomatoes, jalapeño, served with rice, charro beans and queso fresco.", price: 26.99, category_id: "asadero-grill", image_url: P.steak,   is_featured: false, tags: [] },

  // BIRRIA LOVERS
  { id: "bir-1", name: "Pizza Birria",  description: "8 slices birria pizza, onion, cilantro, cheese served with our cheesy fries, bacon, pico de gallo with a cup of consomé.", price: 28.99, category_id: "birria", image_url: P.pizza,   is_featured: true,  tags: [] },
  { id: "bir-2", name: "Birria Nachos", description: "Birria, jalapeño, cilantro, red onion, sour cream, radish, cheese dip and consomé.", price: 19.99, category_id: "birria", image_url: P.nachos,  is_featured: false, tags: [] },
  { id: "bir-3", name: "Ramen Birria",  description: "Ramen soup topped with our birria, corn, cilantro and onion.", price: 12.99, category_id: "birria", image_url: P.soup,    is_featured: false, tags: [] },
  { id: "bir-4", name: "Quesa Birria",  description: "Flour or corn tortillas filled with onion, cilantro, cheese and seasoned barbacoa, served with a cup of consomé, beans and rice.", price: 19.99, category_id: "birria", image_url: P.birria,  is_featured: false, tags: [] },

  // LO MÁS RICO
  { id: "lmr-1",  name: "Mahi Mahi Tacos",     description: "3 mahi tacos, deep fried or grilled, green cabbage, pico de gallo, crema, golden sauce, avocado and queso fresco, served with white rice.", price: 23.99, category_id: "lo-mas-rico", image_url: P.fish,     is_featured: false, tags: [] },
  { id: "lmr-2",  name: "Mexican Fried Rice",   description: "White rice, five way vegetable, special Korean sauce, baby cabbage fried, fried chicken, cheese.", price: 18.99, category_id: "lo-mas-rico", image_url: P.rice,     is_featured: false, tags: [] },
  { id: "lmr-3",  name: "Milanesa",             description: "Your choice of chicken, steak or fish, deep fried served with fries, lettuce, pico de gallo, guacamole, and tortillas.", price: 18.99, category_id: "lo-mas-rico", image_url: P.chicken2, is_featured: false, tags: [] },
  { id: "lmr-4",  name: "Carne Tampiquena",     description: "Skirt steak, served with one enchilada, guacamole, light beans and rice and jalapeño.", price: 24.99, category_id: "lo-mas-rico", image_url: P.steak2,   is_featured: false, tags: [] },
  { id: "lmr-5",  name: "Tilapia Rellena",      description: "Grilled or breaded tilapia topped with pineapple, peppers, mozzarella cheese, served with white rice and garden salad with avocado.", price: 19.99, category_id: "lo-mas-rico", image_url: P.fish,     is_featured: false, tags: [] },
  { id: "lmr-6",  name: "Langostinos",          description: "Prawns, onions, special sauce, cucumbers.", price: 32.99, category_id: "lo-mas-rico", image_url: P.shrimp,   is_featured: false, tags: [] },
  { id: "lmr-7",  name: "Ostiones Regulares",   description: "(12 pcs) Fresh oysters, served on the half shell, accompanied by slices of lime.", price: 25.99, category_id: "lo-mas-rico", image_url: P.oysters,  is_featured: false, tags: [] },
  { id: "lmr-8",  name: "Ostiones Preparados",  description: "(12 pcs) Octopus, cucumber, shrimp, pico de gallo, aguachiles and avocado.", price: 36.99, category_id: "lo-mas-rico", image_url: P.seafood,  is_featured: false, tags: [] },
  { id: "lmr-9",  name: "Mejillones",           description: "(12 pcs) Mussels, special sauce, onions and cucumbers.", price: 21.99, category_id: "lo-mas-rico", image_url: P.seafood,  is_featured: false, tags: [] },
  { id: "lmr-10", name: "Orden de Cangrejo",    description: "Crab legs, guajillo, corn, potatoes, onions, special sauce.", price: 69.99, category_id: "lo-mas-rico", image_url: P.lobster,  is_featured: false, tags: [] },
  { id: "lmr-11", name: "Mariscada",            description: "Shrimp, octopus, lobster sensations, scallops, onions, tomatoes and special sauce.", price: 60.99, category_id: "lo-mas-rico", image_url: P.seafood,  is_featured: false, tags: [] },
  { id: "lmr-12", name: "Cochinita Pibil",      description: "Cochinita pibil marinated for 24 hours house recipe, white rice.", price: 24.99, category_id: "lo-mas-rico", image_url: P.tamal,    is_featured: false, tags: [] },
  { id: "lmr-13", name: "Chapuzón",             description: "Shrimps, octopus, scallops, mussels, crab and special sauce.", price: 28.99, category_id: "lo-mas-rico", image_url: P.shrimp2,  is_featured: false, tags: [] },

  // FROM THE SEA
  { id: "fts-1", name: "Baja Tacos",           description: "Served with rice, black beans, golden sauce, pico de mango, red cabbage. Served with flour tortilla.", price: 19.99, category_id: "from-the-sea", image_url: P.fish,    is_featured: false, tags: [] },
  { id: "fts-2", name: "Salmon N Shrimp",      description: "Salmon, shrimp, BBQ on the bottom. Served with mashed potatoes and vegetables.", price: 28.99, category_id: "from-the-sea", image_url: P.salmon,  is_featured: false, tags: [] },
  { id: "fts-3", name: "Del Mar Trio",         description: "Lobster sensation, tilapia, shrimp, pico de gallo & shredded cheese, served with rice, beans and guacamole salad.", price: 26.99, category_id: "from-the-sea", image_url: P.seafood, is_featured: false, tags: [] },
  { id: "fts-4", name: "Shrimp Chipotle",      description: "Grilled shrimp, onions and a creamy chipotle sauce. Served with white rice, garden salad and avocado.", price: 20.99, category_id: "from-the-sea", image_url: P.shrimp,  is_featured: false, tags: [] },
  { id: "fts-5", name: "Camarones a la Diabla",description: "Grilled shrimp with red sauce, served with white rice, garden salad and avocado.", price: 20.99, category_id: "from-the-sea", image_url: P.shrimp2, is_featured: false, tags: [] },
  { id: "fts-6", name: "Camaron al Mojo de Ajo",description: "Grilled shrimp, cooked with garlic, tomatoes, onions and avocado on a bed of rice.", price: 20.99, category_id: "from-the-sea", image_url: P.shrimp,  is_featured: false, tags: [] },
  { id: "fts-7", name: "Camarones Especial",   description: "Shrimp, scallops, spinach, mushrooms and diced onion. Topped with special sauce served with rice, garden salad and avocado.", price: 22.99, category_id: "from-the-sea", image_url: P.shrimp2, is_featured: false, tags: [] },
  { id: "fts-8", name: "Camarones Momia",      description: "Shrimp wrapped with bacon, served with a garden salad and coconut rice.", price: 26.99, category_id: "from-the-sea", image_url: P.shrimp,  is_featured: false, tags: [] },

  // DEL MAR
  { id: "dm-1",  name: "Piña Suprema",               description: "Fresh pineapple, shrimp, octopus, crab meat, scallops, calamari and red pepper, served with coconut milk, alfredo sauce, coconut rice, tater tots and garlic bread.", price: 32.99, category_id: "del-mar", image_url: P.seafood,  is_featured: true,  tags: [] },
  { id: "dm-2",  name: "Shrimp Cocktail",             description: "Our special sauce with shrimp, chopped onions, cilantro, tomatoes, avocado, jalapeños and served with crackers.", price: 19.99, category_id: "del-mar", image_url: P.shrimp,   is_featured: false, tags: [] },
  { id: "dm-3",  name: "Sampler Ceviche",             description: "Shrimp, fish, octopus, achuchile, tomatoes, onion, jalapeños, cilantro, cucumber and avocado served with chicharrón.", price: 23.99, category_id: "del-mar", image_url: P.ceviche,  is_featured: false, tags: [] },
  { id: "dm-4",  name: "Coctel Patron",               description: "Shrimp, pulpo, ceviche, cucumber, avocado, tomatoes, onion and our special sauce.", price: 26.99, category_id: "del-mar", image_url: P.ceviche2, is_featured: false, tags: [] },
  { id: "dm-5",  name: "Huachinango",                 description: "Breaded fried red snapper, rice, garden salad and fries.", price: 29.99, category_id: "del-mar", image_url: P.fish,     is_featured: false, tags: [] },
  { id: "dm-6",  name: "Mojarra",                     description: "Breaded fried mojarra, rice, garden salad and fries.", price: 26.99, category_id: "del-mar", image_url: P.fish,     is_featured: false, tags: [] },
  { id: "dm-7",  name: "Monster Ceviche",             description: "Tuna steak, scallops, octopus, shrimp, mango, red onion, cucumber, serrano and avocado. Served with Doritos.", price: 29.99, category_id: "del-mar", image_url: P.ceviche,  is_featured: false, tags: [] },
  { id: "dm-8",  name: "El Molcajete de Mariscos",    description: "Crab legs, octopus, shrimp, scallops, mussels and special sauce.", price: 32.99, category_id: "del-mar", image_url: P.seafood,  is_featured: false, tags: [] },
  { id: "dm-9",  name: "Paella",                      description: "A bed of rice, shrimp, mussels, calamari, octopus.", price: 27.90, category_id: "del-mar", image_url: P.seafood,  is_featured: false, tags: [] },
  { id: "dm-10", name: "Bomb Tuna",                   description: "Tuna steak, topped with homemade special sauce, red onion, cucumber and serrano.", price: 21.99, category_id: "del-mar", image_url: P.fish,     is_featured: false, tags: [] },
  { id: "dm-11", name: "Aguachiles Culichi",          description: "Half green aguachiles, red aguachile, cucumber, onion and 1 shot of oysters and avocado.", price: 29.99, category_id: "del-mar", image_url: P.ceviche2, is_featured: false, tags: [] },
  { id: "dm-12", name: "Aguachiles",                  description: "Choice of Green (Verdes), Red (Rojo), Mango or Negros.", price: 24.99, category_id: "del-mar", image_url: P.ceviche,  is_featured: false, tags: [] },
  { id: "dm-13", name: "Aguachiles Tostada",          description: "One tostada with choice of aguachile flavor.", price: 8.99, category_id: "del-mar", image_url: P.ceviche2, is_featured: false, tags: [] },
  { id: "dm-14", name: "La Torre de Mariscos",        description: "Aguachile, shrimp, pescado, octopus, ceviche and avocado, topped with camarones roca.", price: 34.99, category_id: "del-mar", image_url: P.seafood,  is_featured: false, tags: [] },
  { id: "dm-15", name: "Seafood Pasta",               description: "Penne pasta, shrimp, mussels, scallops, topped with alfredo sauce and chipotle sauce.", price: 21.99, category_id: "del-mar", image_url: P.pasta,    is_featured: false, tags: [] },
  { id: "dm-16", name: "Cajun",                       description: "Mussels, sausage, shrimp head on, peel shrimp, crab leg, potatoes, corn, all mixed in our special Cajun sauce.", price: 69.99, category_id: "del-mar", image_url: P.seafood,  is_featured: false, tags: [] },
  { id: "dm-17", name: "Langosta Veracruzana",        description: "A bed of white rice, lobster tail, calamari, octopus, peel shrimp, lobster imitation topped with our special creamy wine sauce.", price: 32.99, category_id: "del-mar", image_url: P.lobster,  is_featured: false, tags: [] },
  { id: "dm-18", name: "7 Mares",                     description: "Crab legs, headless shrimp, mussels, octopus, scallops, tilapia, seafood soup, onion and cilantro.", price: 27.99, category_id: "del-mar", image_url: P.seafood,  is_featured: false, tags: [] },
  { id: "dm-19", name: "Seafood Family Tray",         description: "Crab leg, red snapper, camarones, mojarra, prawns, mussels, fried fish, corn and potatoes.", price: 220.00, category_id: "del-mar", image_url: P.seafood,  is_featured: false, tags: [] },
  { id: "dm-20", name: "Cucas",                       description: "Shrimp, onion, cucumber and special sauce.", price: 24.99, category_id: "del-mar", image_url: P.shrimp2,  is_featured: false, tags: [] },
  { id: "dm-21", name: "Chicharrón Pescado",          description: null, price: 14.99, category_id: "del-mar", image_url: P.fish,     is_featured: false, tags: [] },
  { id: "dm-22", name: "Grilled Octopus",             description: null, price: 69.99, category_id: "del-mar", image_url: P.seafood,  is_featured: false, tags: [] },
  { id: "dm-23", name: "Coctel Vuelve a la Vida",     description: "Shrimp, octopus, lobster sensations, scallops, oysters, tomatoes, onions, cilantro, avocado, cucumber and seafood cocktail sauce.", price: 26.99, category_id: "del-mar", image_url: P.ceviche,  is_featured: false, tags: [] },
  { id: "dm-24", name: "Ceviche",                     description: "Lime cooked and mixed with onions, cilantro, tomatoes, cucumber, jalapeños and avocado.", price: 21.99, category_id: "del-mar", image_url: P.ceviche2, is_featured: false, tags: [] },
  { id: "dm-25", name: "Ceviche Tostada (1)",         description: null, price: 8.99, category_id: "del-mar", image_url: P.ceviche,  is_featured: false, tags: [] },
  { id: "dm-26", name: "Ceviche Loco",                description: "Mixed ceviche, crab meat, octopus, aguachiles, fresh pineapple, onion, cucumber and cilantro.", price: 31.99, category_id: "del-mar", image_url: P.ceviche2, is_featured: false, tags: [] },
  { id: "dm-27", name: "Create Your Own Combo — Pick Two",  description: null, price: 13.99, category_id: "del-mar", image_url: P.seafood,  is_featured: false, tags: [] },
  { id: "dm-28", name: "Create Your Own Combo — Pick Three",description: null, price: 16.99, category_id: "del-mar", image_url: P.seafood,  is_featured: false, tags: [] },

  // VEGGIES
  { id: "veg-1", name: "Impossible Burger",          description: "Impossible patty, pepper jack cheese, pepper, mushroom, avocado, lettuce, tomato, and onion.", price: 15.99, category_id: "veggies", image_url: P.vegBurger, is_featured: false, tags: ["vegetarian"] },
  { id: "veg-2", name: "Impossible Nachos",          description: "Impossible meat, beans, corn, jalapeños, cilantro, topped with sour cream and cheese sauce.", price: 15.99, category_id: "veggies", image_url: P.nachos,    is_featured: false, tags: ["vegetarian"] },
  { id: "veg-3", name: "Impossible Burger with Fries",description: "Impossible patty, cheese, peppers, mushrooms, avocado, lettuce, tomato, and onion served with french fries.", price: 15.99, category_id: "veggies", image_url: P.vegBurger, is_featured: false, tags: ["vegetarian"] },
  { id: "veg-4", name: "Veggie Alambre",             description: "Four flour tortillas, onion, tomatoes, peppers, pineapple, zucchini, nopal, roasted corn, mushrooms and cheese. Served with rice, beans and guacamole salad.", price: 14.99, category_id: "veggies", image_url: P.veggie,    is_featured: false, tags: ["vegetarian"] },
  { id: "veg-5", name: "Veggie Monster Burrito",     description: "Filled with black beans, rice, corn, zucchini, onions, bell peppers, mushroom topped with cheese sauce and sour cream.", price: 14.99, category_id: "veggies", image_url: P.burrito,    is_featured: false, tags: ["vegetarian"] },
  { id: "veg-6", name: "Veggie Fajitas",             description: "Bell peppers, onions, zucchini, tomatoes, and mushrooms, served with rice, beans, lettuce, guacamole, sour cream and pico de gallo.", price: 14.99, category_id: "veggies", image_url: P.fajitas,    is_featured: false, tags: ["vegetarian"] },
  { id: "veg-7", name: "Veggie Taco Salad",          description: "Grilled bell peppers, onions, mushroom, tomato, zucchini, lettuce, sour cream and corn.", price: 10.99, category_id: "veggies", image_url: P.salad,      is_featured: false, tags: ["vegetarian"] },
  { id: "veg-8", name: "Veggie Quesadilla",          description: "Quesadilla filled with mushroom, onions, tomato topped with cheese sauce served with rice and beans.", price: 12.99, category_id: "veggies", image_url: P.quesadilla, is_featured: false, tags: ["vegetarian"] },

  // KIDS
  { id: "kid-1",  name: "Taco",                       description: "Served with rice and beans.", price: 8.99, category_id: "kids", image_url: P.tacos,    is_featured: false, tags: [] },
  { id: "kid-2",  name: "Burrito",                    description: "Served with rice and beans.", price: 8.99, category_id: "kids", image_url: P.burrito2, is_featured: false, tags: [] },
  { id: "kid-3",  name: "One Cheese Quesadilla",      description: "Served choice of fries or rice.", price: 8.99, category_id: "kids", image_url: P.quesadilla, is_featured: false, tags: [] },
  { id: "kid-4",  name: "Hamburger",                  description: "With lettuce, tomatoes, cheese and served with french fries.", price: 8.99, category_id: "kids", image_url: P.kidsMeal, is_featured: false, tags: [] },
  { id: "kid-5",  name: "Chicken Tenders",            description: "Served with french fries.", price: 8.99, category_id: "kids", image_url: P.wings,    is_featured: false, tags: [] },
  { id: "kid-6",  name: "Mac and Cheese",             description: "Served with french fries.", price: 8.99, category_id: "kids", image_url: P.kidsMeal, is_featured: false, tags: [] },
  { id: "kid-7",  name: "Pepperoni Pizza",            description: "Served with french fries.", price: 8.99, category_id: "kids", image_url: P.pizza,    is_featured: false, tags: [] },
  { id: "kid-8",  name: "Grilled Cheese Bread",       description: "Served with french fries.", price: 8.99, category_id: "kids", image_url: P.kidsMeal, is_featured: false, tags: [] },
  { id: "kid-9",  name: "Mozzarella Cheese Sticks",   description: "Served with french fries.", price: 8.99, category_id: "kids", image_url: P.kidsMeal, is_featured: false, tags: [] },
  { id: "kid-10", name: "Arroz con Pollo",            description: "Bed of rice topped with cheese sauce and grilled chicken.", price: 8.99, category_id: "kids", image_url: P.chicken,  is_featured: false, tags: [] },

  // A LA CARTE
  { id: "alc-1",  name: "Crunchy Taco (1)",    description: "Your choice of ground beef or chicken, topped with lettuce and cheese.", price: 2.99, category_id: "a-la-carte", image_url: P.tacos,     is_featured: false, tags: [] },
  { id: "alc-2",  name: "Crunchy Tacos (3)",   description: "Your choice of ground beef or chicken, topped with lettuce and cheese.", price: 7.99, category_id: "a-la-carte", image_url: P.tacos2,    is_featured: false, tags: [] },
  { id: "alc-3",  name: "Soft Taco (1)",       description: "Your choice of ground beef or chicken, topped with lettuce and cheese.", price: 2.99, category_id: "a-la-carte", image_url: P.tacos,     is_featured: false, tags: [] },
  { id: "alc-4",  name: "Soft Tacos (3)",      description: "Your choice of ground beef or chicken, topped with lettuce and cheese.", price: 7.99, category_id: "a-la-carte", image_url: P.tacos2,    is_featured: false, tags: [] },
  { id: "alc-5",  name: "Enchilada (1)",       description: "Your choice of ground beef or chicken topped with mild red sauce.", price: 2.99, category_id: "a-la-carte", image_url: P.enchilada,  is_featured: false, tags: [] },
  { id: "alc-6",  name: "Enchiladas (3)",      description: "Your choice of ground beef or chicken topped with mild red sauce.", price: 8.99, category_id: "a-la-carte", image_url: P.enchilada2, is_featured: false, tags: [] },
  { id: "alc-7",  name: "Burrito",             description: "Your choice of ground beef, chicken or beans topped with red sauce.", price: 8.99, category_id: "a-la-carte", image_url: P.burrito,    is_featured: false, tags: [] },
  { id: "alc-8",  name: "Chile Relleno",       description: "With poblano sauce and stuffed with cheese.", price: 6.99, category_id: "a-la-carte", image_url: P.jalap,      is_featured: false, tags: [] },
  { id: "alc-9",  name: "Chalupa",             description: "Your choice of ground beef, chicken or beans topped with lettuce, guacamole and tomatoes.", price: 6.99, category_id: "a-la-carte", image_url: P.sopes,      is_featured: false, tags: [] },
  { id: "alc-10", name: "Tostada",             description: "Your choice of ground beef, chicken or beans topped with tomato, lettuce and guacamole.", price: 5.25, category_id: "a-la-carte", image_url: P.tacos,      is_featured: false, tags: [] },
  { id: "alc-11", name: "Tamal",               description: "Topped with ground beef, cheese and sauce, stuffed with pork meat.", price: 5.25, category_id: "a-la-carte", image_url: P.tamal,      is_featured: false, tags: [] },
  { id: "alc-12", name: "Chimichanga",         description: "Your choice of ground beef or chicken.", price: 6.99, category_id: "a-la-carte", image_url: P.burrito2,   is_featured: false, tags: [] },

  // SIDES
  { id: "side-1",  name: "Rice",             description: null, price: 3.99, category_id: "sides", image_url: P.rice,  is_featured: false, tags: [] },
  { id: "side-2",  name: "Beans",            description: null, price: 3.99, category_id: "sides", image_url: P.rice,  is_featured: false, tags: [] },
  { id: "side-3",  name: "Lettuce",          description: null, price: 1.99, category_id: "sides", image_url: P.salad, is_featured: false, tags: [] },
  { id: "side-4",  name: "Tomato",           description: null, price: 1.99, category_id: "sides", image_url: P.salad, is_featured: false, tags: [] },
  { id: "side-5",  name: "Sour Cream",       description: null, price: 1.99, category_id: "sides", image_url: P.dip,   is_featured: false, tags: [] },
  { id: "side-6",  name: "Pico de Gallo",    description: null, price: 2.99, category_id: "sides", image_url: P.guac,  is_featured: false, tags: [] },
  { id: "side-7",  name: "Onions",           description: null, price: 1.49, category_id: "sides", image_url: P.salad, is_featured: false, tags: [] },
  { id: "side-8",  name: "Cilantro",         description: null, price: 0.99, category_id: "sides", image_url: P.salad, is_featured: false, tags: [] },
  { id: "side-9",  name: "Pico de Mango",    description: null, price: 2.69, category_id: "sides", image_url: P.salad, is_featured: false, tags: [] },
  { id: "side-10", name: "Jalapeños",        description: null, price: 1.50, category_id: "sides", image_url: P.jalap, is_featured: false, tags: [] },
  { id: "side-11", name: "Avocado Slices",   description: null, price: 5.25, category_id: "sides", image_url: P.guac,  is_featured: false, tags: [] },
  { id: "side-12", name: "Shredded Cheese",  description: null, price: 1.99, category_id: "sides", image_url: P.dip,   is_featured: false, tags: [] },
  { id: "side-13", name: "French Fries",     description: null, price: 4.99, category_id: "sides", image_url: P.fries, is_featured: false, tags: [] },
  { id: "side-14", name: "Mashed Potatoes",  description: null, price: 3.25, category_id: "sides", image_url: P.rice,  is_featured: false, tags: [] },
  { id: "side-15", name: "Guacamole Salad",  description: "Lettuce, guacamole and tomato.", price: 3.99, category_id: "sides", image_url: P.guac,  is_featured: false, tags: [] },
];
